//! Retention of durable verification evidence through cache GC.

use fs2::FileExt;
use serde_json::Value;
use std::fs::{self, File, OpenOptions};
use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use tempfile::tempdir;

const GROVE: &str = env!("CARGO_BIN_EXE_grove");

fn git(dir: &Path, args: &[&str]) {
    let status = Command::new("git")
        .args(args)
        .current_dir(dir)
        .status()
        .unwrap();
    assert!(status.success(), "git {args:?} failed");
}

fn init(repo: &Path) {
    std::fs::create_dir_all(repo.join("src")).unwrap();
    git(repo, &["init", "-q"]);
    git(repo, &["config", "core.autocrlf", "false"]);
    git(repo, &["config", "user.email", "evidence@example.test"]);
    git(repo, &["config", "user.name", "evidence-test"]);
    let origin = repo.parent().unwrap().join("portable-origin.git");
    git(repo, &["remote", "add", "origin", origin.to_str().unwrap()]);
    std::fs::write(
        repo.join("Cargo.toml"),
        "[package]\nname='evidence_fixture'\nversion='0.1.0'\nedition='2021'\n",
    )
    .unwrap();
    std::fs::write(
        repo.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"evidence_fixture\"\nversion = \"0.1.0\"\n",
    )
    .unwrap();
    std::fs::write(repo.join("src/lib.rs"), "pub fn version() -> u8 { 0 }\n").unwrap();
    std::fs::write(
        repo.join(".grove.toml"),
        r#"
[verification]
required = ["gate"]

[verification.profiles.gate]
continue_on_failure = false
portable = true
commands = [
  { argv = ["cargo", "-Vv"], allow_zero_tests = false },
  { argv = ["cargo", "--version"], allow_zero_tests = false },
]
"#,
    )
    .unwrap();
    git(repo, &["add", "-A"]);
    git(repo, &["commit", "-q", "-m", "init"]);
}

fn run(repo: &Path, cache: &Path, args: &[&str]) -> Output {
    Command::new(GROVE)
        .args(args)
        .current_dir(repo)
        .env("GROVE_CACHE_ROOT", cache)
        .env_remove("CARGO_TARGET_X86_64_PC_WINDOWS_MSVC_LINKER")
        .output()
        .unwrap()
}

fn evidence_lock(cache: &Path) -> File {
    let locks = cache.join("locks");
    fs::create_dir_all(&locks).unwrap();
    OpenOptions::new()
        .create(true)
        .read(true)
        .write(true)
        .truncate(false)
        .open(locks.join("verification-evidence.lock"))
        .unwrap()
}

fn begin(repo: &Path, cache: &Path) -> String {
    let output = run(
        repo,
        cache,
        &[
            "task", "begin", "--agent", "alice", "--task", "evidence", "--scope", "src",
        ],
    );
    assert!(output.status.success());
    serde_json::from_slice::<Value>(&output.stdout).unwrap()["task"]["id"]
        .as_str()
        .unwrap()
        .to_string()
}

fn repo_dir(cache: &Path, kind: &str) -> PathBuf {
    std::fs::read_dir(cache.join(kind))
        .unwrap()
        .next()
        .unwrap()
        .unwrap()
        .path()
}

fn json_count(dir: &Path) -> usize {
    std::fs::read_dir(dir)
        .unwrap()
        .filter_map(|entry| entry.ok())
        .filter(|entry| {
            entry
                .path()
                .extension()
                .is_some_and(|extension| extension == "json")
        })
        .count()
}

fn portable_receipts(cache: &Path) -> Vec<Value> {
    fs::read_dir(repo_dir(cache, "receipts"))
        .unwrap()
        .map(|entry| {
            serde_json::from_slice::<Value>(&fs::read(entry.unwrap().path()).unwrap()).unwrap()
        })
        .filter(|receipt| receipt["portable"].is_object())
        .collect()
}

fn earliest_run(cache: &Path) -> String {
    let mut runs = fs::read_dir(repo_dir(cache, "verification-runs"))
        .unwrap()
        .filter_map(|entry| entry.ok())
        .map(|entry| serde_json::from_slice::<Value>(&fs::read(entry.path()).unwrap()).unwrap())
        .collect::<Vec<_>>();
    runs.sort_by_key(|run| {
        (
            run["completed_at_nanos"].as_u64().unwrap(),
            run["run_id"].as_str().unwrap().to_string(),
        )
    });
    runs[0]["run_id"].as_str().unwrap().to_string()
}

fn mark_release_run(cache: &Path) {
    let run_id = earliest_run(cache);
    for entry in fs::read_dir(repo_dir(cache, "receipts")).unwrap() {
        let path = entry.unwrap().path();
        let mut receipt: Value = serde_json::from_slice(&fs::read(&path).unwrap()).unwrap();
        if receipt["run_id"] == run_id {
            receipt["lane"]["tag"] = Value::String("release-freeze-test".into());
            fs::write(path, serde_json::to_vec_pretty(&receipt).unwrap()).unwrap();
        }
    }
}

fn verify_task_twice(repo: &Path, cache: &Path, id: &str) {
    for version in [1, 2] {
        fs::write(
            repo.join("src/lib.rs"),
            format!("pub fn version() -> u8 {{ {version} }}\n"),
        )
        .unwrap();
        assert!(
            run(repo, cache, &["verify", "gate", "--task-id", id])
                .status
                .success()
        );
    }
}

#[test]
fn gc_keeps_the_latest_fresh_task_run_and_its_snapshot_graph() {
    let base = tempdir().unwrap();
    let repo = base.path().join("repo");
    let cache = base.path().join("cache");
    init(&repo);
    let id = begin(&repo, &cache);

    verify_task_twice(&repo, &cache, &id);

    assert_eq!(json_count(&repo_dir(&cache, "verification-runs")), 2);
    assert_eq!(json_count(&repo_dir(&cache, "receipts")), 4);
    assert_eq!(json_count(&repo_dir(&cache, "snapshots")), 3);

    let output = run(&repo, &cache, &["cache", "gc"]);
    assert!(output.status.success());
    let report: Value = serde_json::from_slice(&output.stdout).unwrap();
    assert_eq!(json_count(&repo_dir(&cache, "verification-runs")), 1);
    assert_eq!(json_count(&repo_dir(&cache, "receipts")), 2);
    assert_eq!(json_count(&repo_dir(&cache, "snapshots")), 2);
    assert!(report["evidence_reclaimed"].as_array().unwrap().len() >= 4);

    let finished = run(&repo, &cache, &["task", "finish", "--task-id", &id]);
    assert!(
        finished.status.success(),
        "{}",
        String::from_utf8_lossy(&finished.stderr)
    );
}

#[test]
fn gc_bounds_taskless_verification_to_its_latest_profile_run() {
    let base = tempdir().unwrap();
    let repo = base.path().join("repo");
    let cache = base.path().join("cache");
    init(&repo);

    assert!(run(&repo, &cache, &["verify", "gate"]).status.success());
    assert!(run(&repo, &cache, &["verify", "gate"]).status.success());
    assert_eq!(json_count(&repo_dir(&cache, "verification-runs")), 2);
    assert_eq!(json_count(&repo_dir(&cache, "receipts")), 4);
    assert_eq!(json_count(&repo_dir(&cache, "snapshots")), 1);

    let output = run(&repo, &cache, &["cache", "gc"]);
    assert!(output.status.success());
    assert_eq!(json_count(&repo_dir(&cache, "verification-runs")), 1);
    assert_eq!(json_count(&repo_dir(&cache, "receipts")), 2);
    assert_eq!(json_count(&repo_dir(&cache, "snapshots")), 1);
}

#[test]
fn gc_keeps_recent_clean_heads_for_portable_receipt_reuse() {
    let base = tempdir().unwrap();
    let repo = base.path().join("repo");
    let cache = base.path().join("cache");
    init(&repo);

    assert!(run(&repo, &cache, &["verify", "gate"]).status.success());
    fs::write(repo.join("src/lib.rs"), "pub fn version() -> u8 { 1 }\n").unwrap();
    git(&repo, &["add", "src/lib.rs"]);
    git(&repo, &["commit", "-q", "-m", "next"]);
    assert!(run(&repo, &cache, &["verify", "gate"]).status.success());

    let portable = portable_receipts(&cache);
    assert_eq!(portable.len(), 4, "portable receipts: {portable:#?}");
    assert!(run(&repo, &cache, &["cache", "gc"]).status.success());
    assert_eq!(json_count(&repo_dir(&cache, "verification-runs")), 2);
    assert_eq!(json_count(&repo_dir(&cache, "receipts")), 4);
    assert_eq!(json_count(&repo_dir(&cache, "snapshots")), 2);
}

#[test]
fn gc_keeps_clean_task_receipts_for_portable_reuse() {
    let base = tempdir().unwrap();
    let repo = base.path().join("repo");
    let cache = base.path().join("cache");
    init(&repo);
    let id = begin(&repo, &cache);

    assert!(
        run(&repo, &cache, &["verify", "gate", "--task-id", &id])
            .status
            .success()
    );
    fs::write(repo.join("src/lib.rs"), "pub fn version() -> u8 { 1 }\n").unwrap();
    git(&repo, &["add", "src/lib.rs"]);
    git(&repo, &["commit", "-q", "-m", "next"]);
    assert!(
        run(&repo, &cache, &["verify", "gate", "--task-id", &id])
            .status
            .success()
    );

    assert!(run(&repo, &cache, &["cache", "gc"]).status.success());
    assert_eq!(json_count(&repo_dir(&cache, "verification-runs")), 2);
    assert_eq!(json_count(&repo_dir(&cache, "receipts")), 4);
    assert_eq!(json_count(&repo_dir(&cache, "snapshots")), 2);
}

#[test]
fn gc_keeps_frozen_release_receipts_when_a_newer_taskless_run_exists() {
    let base = tempdir().unwrap();
    let repo = base.path().join("repo");
    let cache = base.path().join("cache");
    init(&repo);

    assert!(run(&repo, &cache, &["verify", "gate"]).status.success());
    assert!(run(&repo, &cache, &["verify", "gate"]).status.success());
    mark_release_run(&cache);

    assert!(run(&repo, &cache, &["cache", "gc"]).status.success());
    assert_eq!(json_count(&repo_dir(&cache, "verification-runs")), 2);
    assert_eq!(json_count(&repo_dir(&cache, "receipts")), 4);
}

#[test]
fn gc_waits_for_every_shared_evidence_holder() {
    let base = tempdir().unwrap();
    let repo = base.path().join("repo");
    let cache = base.path().join("cache");
    init(&repo);
    assert!(run(&repo, &cache, &["verify", "gate"]).status.success());
    assert!(run(&repo, &cache, &["verify", "gate"]).status.success());

    let first = evidence_lock(&cache);
    let second = evidence_lock(&cache);
    FileExt::lock_shared(&first).unwrap();
    FileExt::lock_shared(&second).unwrap();
    let blocked = || {
        let output = run(&repo, &cache, &["cache", "gc"]);
        assert!(output.status.success());
        let report: Value = serde_json::from_slice(&output.stdout).unwrap();
        assert!(report["evidence_reclaimed"].as_array().unwrap().is_empty());
        assert_eq!(json_count(&repo_dir(&cache, "verification-runs")), 2);
        assert_eq!(json_count(&repo_dir(&cache, "receipts")), 4);
        assert_eq!(json_count(&repo_dir(&cache, "snapshots")), 1);
    };
    blocked();
    drop(first);
    blocked();
    drop(second);

    let output = run(&repo, &cache, &["cache", "gc"]);
    assert!(output.status.success());
    let report: Value = serde_json::from_slice(&output.stdout).unwrap();
    assert!(!report["evidence_reclaimed"].as_array().unwrap().is_empty());
    assert_eq!(json_count(&repo_dir(&cache, "verification-runs")), 1);
    assert_eq!(json_count(&repo_dir(&cache, "receipts")), 2);
    assert_eq!(json_count(&repo_dir(&cache, "snapshots")), 1);
}

#[test]
fn gc_skips_a_repository_with_malformed_evidence_metadata() {
    for kind in ["verification-runs", "tasks", "receipts"] {
        let base = tempdir().unwrap();
        let repo = base.path().join("repo");
        let cache = base.path().join("cache");
        init(&repo);
        let id = begin(&repo, &cache);
        verify_task_twice(&repo, &cache, &id);
        fs::write(repo_dir(&cache, kind).join("corrupt.json"), b"{").unwrap();
        let expected = [
            json_count(&repo_dir(&cache, "verification-runs")),
            json_count(&repo_dir(&cache, "receipts")),
            json_count(&repo_dir(&cache, "snapshots")),
        ];

        let output = run(&repo, &cache, &["cache", "gc"]);
        assert!(output.status.success(), "{kind}");
        let report: Value = serde_json::from_slice(&output.stdout).unwrap();
        assert!(report["evidence_reclaimed"].as_array().unwrap().is_empty());
        assert_eq!(
            [
                json_count(&repo_dir(&cache, "verification-runs")),
                json_count(&repo_dir(&cache, "receipts")),
                json_count(&repo_dir(&cache, "snapshots")),
            ],
            expected,
            "{kind}"
        );
    }
}
