//! Portable clean-checkout verification evidence across two clones of one origin.

use serde_json::Value;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use tempfile::tempdir;

const GROVE: &str = env!("CARGO_BIN_EXE_grove");

fn git(dir: &Path, args: &[&str]) {
    let status = Command::new("git")
        .args(args)
        .current_dir(dir)
        .status()
        .unwrap();
    assert!(status.success(), "git {args:?} failed");
}

fn run(repo: &Path, cache: &Path, args: &[&str]) -> Output {
    Command::new(GROVE)
        .args(args)
        .current_dir(repo)
        .env("GROVE_CACHE_ROOT", cache)
        .output()
        .unwrap()
}

fn query(repo: &Path, cache: &Path) -> Value {
    let output = run(repo, cache, &["verify", "query", "gate"]);
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    serde_json::from_slice(&output.stdout).unwrap()
}

fn profile(repo: &Path, command: &[&str]) {
    let argv = command
        .iter()
        .map(|argument| format!("{argument:?}"))
        .collect::<Vec<_>>()
        .join(", ");
    fs::write(
        repo.join(".grove.toml"),
        format!(
            "[verification.profiles.gate]\ncontinue_on_failure = false\nportable = true\nportable_env = [\"NEXUS_RELEASE_MODE\"]\ncommands = [{{ argv = [{argv}], allow_zero_tests = false }}]\n"
        ),
    )
    .unwrap();
}

fn local_only_profile(repo: &Path) {
    fs::write(
        repo.join(".grove.toml"),
        "[verification.profiles.gate]\ncontinue_on_failure = false\ncommands = [{ argv = [\"cargo\", \"-Vv\"], allow_zero_tests = false }]\n",
    )
    .unwrap();
}

fn configure_clone(repo: &Path) {
    git(repo, &["config", "user.email", "portable@example.test"]);
    git(repo, &["config", "user.name", "portable-test"]);
}

fn fixture() -> (tempfile::TempDir, PathBuf, PathBuf, PathBuf, PathBuf) {
    fixture_with_command(&["cargo", "-Vv"])
}

fn fixture_with_command(
    command: &[&str],
) -> (tempfile::TempDir, PathBuf, PathBuf, PathBuf, PathBuf) {
    let base = tempdir().unwrap();
    let origin = base.path().join("origin.git");
    let source = base.path().join("source");
    let dev = base.path().join("development");
    let deploy = base.path().join("deployment");
    let cache = base.path().join("cache");
    fs::create_dir_all(source.join("src")).unwrap();
    git(
        base.path(),
        &["init", "--bare", "-q", origin.to_str().unwrap()],
    );
    git(&source, &["init", "-q"]);
    git(&source, &["config", "user.email", "portable@example.test"]);
    git(&source, &["config", "user.name", "portable-test"]);
    fs::write(
        source.join("Cargo.toml"),
        "[package]\nname='portable_fixture'\nversion='0.1.0'\nedition='2021'\n",
    )
    .unwrap();
    fs::write(
        source.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"portable_fixture\"\nversion = \"0.1.0\"\n",
    )
    .unwrap();
    fs::write(
        source.join("src/lib.rs"),
        "pub fn present() -> bool { true }\n",
    )
    .unwrap();
    fs::write(source.join(".gitignore"), "ignored-input\n").unwrap();
    profile(&source, command);
    git(&source, &["add", "-A"]);
    git(&source, &["commit", "-q", "-m", "initial"]);
    git(&source, &["branch", "-M", "main"]);
    git(
        &source,
        &["remote", "add", "origin", origin.to_str().unwrap()],
    );
    git(&source, &["push", "-q", "-u", "origin", "main"]);
    git(
        base.path(),
        &[
            "--git-dir",
            origin.to_str().unwrap(),
            "symbolic-ref",
            "HEAD",
            "refs/heads/main",
        ],
    );
    git(
        base.path(),
        &[
            "clone",
            "-q",
            origin.to_str().unwrap(),
            dev.to_str().unwrap(),
        ],
    );
    git(
        base.path(),
        &[
            "clone",
            "-q",
            origin.to_str().unwrap(),
            deploy.to_str().unwrap(),
        ],
    );
    configure_clone(&dev);
    configure_clone(&deploy);
    (base, dev, deploy, cache, origin)
}

fn begins(repo: &Path, cache: &Path) -> String {
    let output = run(
        repo,
        cache,
        &[
            "task", "begin", "--agent", "nexus", "--task", "verify", "--scope", "src",
        ],
    );
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    serde_json::from_slice::<Value>(&output.stdout).unwrap()["task"]["id"]
        .as_str()
        .unwrap()
        .to_string()
}

fn assert_miss(report: &Value) {
    assert!(report["eligible"].as_bool().unwrap());
    assert!(!report["matched"].as_bool().unwrap());
    assert!(report["matches"].as_array().unwrap().is_empty());
}

fn assert_unmatched(report: &Value) {
    assert!(!report["matched"].as_bool().unwrap());
    assert!(report["matches"].as_array().unwrap().is_empty());
}

#[test]
fn query_reuses_only_matching_clean_receipts_from_another_clone() {
    let (_base, dev, deploy, cache, origin) = fixture();
    let task_id = begins(&dev, &cache);
    let verified = run(&dev, &cache, &["verify", "gate", "--task-id", &task_id]);
    assert!(
        verified.status.success(),
        "{}",
        String::from_utf8_lossy(&verified.stderr)
    );
    let receipt: Value = serde_json::from_slice(&verified.stdout).unwrap();
    assert!(receipt["receipts"][0]["portable"].is_object());
    assert_eq!(
        receipt["receipts"][0]["lane"]["policy_sha256"]
            .as_str()
            .unwrap()
            .len(),
        64
    );

    let matched = query(&deploy, &cache);
    assert!(matched["eligible"].as_bool().unwrap());
    assert!(matched["matched"].as_bool().unwrap());
    assert_eq!(matched["matches"].as_array().unwrap().len(), 1);
    assert_eq!(
        matched["matches"][0]["receipts"][0]["argv"],
        serde_json::json!(["cargo", "-Vv"])
    );

    fs::write(deploy.join("untracked.txt"), "dirty\n").unwrap();
    let dirty = query(&deploy, &cache);
    assert!(!dirty["eligible"].as_bool().unwrap());
    assert!(!dirty["matched"].as_bool().unwrap());
    fs::remove_file(deploy.join("untracked.txt")).unwrap();

    profile(&deploy, &["cargo", "--version"]);
    assert_unmatched(&query(&deploy, &cache));
    profile(&deploy, &["cargo", "-Vv"]);
    assert!(query(&deploy, &cache)["matched"].as_bool().unwrap());

    let changed_environment = Command::new(GROVE)
        .args(["verify", "query", "gate"])
        .current_dir(&deploy)
        .env("GROVE_CACHE_ROOT", &cache)
        .env("RUSTFLAGS", "-Cdebuginfo=1")
        .output()
        .unwrap();
    assert!(changed_environment.status.success());
    let changed_environment: Value = serde_json::from_slice(&changed_environment.stdout).unwrap();
    assert_miss(&changed_environment);

    let changed_profile = Command::new(GROVE)
        .args(["verify", "query", "gate"])
        .current_dir(&deploy)
        .env("GROVE_CACHE_ROOT", &cache)
        .env("CARGO_PROFILE_RELEASE_LTO", "true")
        .output()
        .unwrap();
    assert!(changed_profile.status.success());
    let changed_profile: Value = serde_json::from_slice(&changed_profile.stdout).unwrap();
    assert_miss(&changed_profile);

    let undeclared_environment = Command::new(GROVE)
        .args(["verify", "query", "gate"])
        .current_dir(&deploy)
        .env("GROVE_CACHE_ROOT", &cache)
        .env("NEXUS_UNDECLARED_VARIABLE", "changed")
        .output()
        .unwrap();
    assert!(undeclared_environment.status.success());
    let undeclared_environment: Value =
        serde_json::from_slice(&undeclared_environment.stdout).unwrap();
    assert!(undeclared_environment["matched"].as_bool().unwrap());

    let declared_environment = Command::new(GROVE)
        .args(["verify", "query", "gate"])
        .current_dir(&deploy)
        .env("GROVE_CACHE_ROOT", &cache)
        .env("NEXUS_RELEASE_MODE", "changed")
        .output()
        .unwrap();
    assert!(declared_environment.status.success());
    let declared_environment: Value = serde_json::from_slice(&declared_environment.stdout).unwrap();
    assert_miss(&declared_environment);

    fs::write(deploy.join("ignored-input"), "different\n").unwrap();
    let ignored = query(&deploy, &cache);
    assert!(!ignored["eligible"].as_bool().unwrap());
    assert_unmatched(&ignored);
    fs::remove_file(deploy.join("ignored-input")).unwrap();

    git(
        &deploy,
        &["remote", "set-url", "origin", "/another/clean-origin.git"],
    );
    assert_miss(&query(&deploy, &cache));
    git(
        &deploy,
        &["remote", "set-url", "origin", origin.to_str().unwrap()],
    );

    fs::write(
        deploy.join("src/lib.rs"),
        "pub fn present() -> bool { false }\n",
    )
    .unwrap();
    git(&deploy, &["add", "src/lib.rs"]);
    git(&deploy, &["commit", "-q", "-m", "different head"]);
    assert_miss(&query(&deploy, &cache));
}

#[test]
fn query_reuses_native_cargo_test_without_lane_path_identity() {
    let (_base, dev, deploy, cache, _origin) = fixture_with_command(&["cargo", "test"]);
    let verified = run(&dev, &cache, &["verify", "gate"]);
    assert!(
        verified.status.success(),
        "{}",
        String::from_utf8_lossy(&verified.stderr),
    );
    let receipt: Value = serde_json::from_slice(&verified.stdout).unwrap();
    let lane = PathBuf::from(receipt["receipts"][0]["lane"]["path"].as_str().unwrap());
    assert!(lane.join("target").is_dir());

    let matched = query(&deploy, &cache);
    assert!(matched["eligible"].as_bool().unwrap());
    assert!(matched["matched"].as_bool().unwrap());
}

#[test]
fn query_rejects_legacy_receipts_without_a_portable_binding() {
    let (_base, dev, deploy, cache, _origin) = fixture();
    let verified = run(&dev, &cache, &["verify", "gate"]);
    assert!(verified.status.success());
    assert!(query(&deploy, &cache)["matched"].as_bool().unwrap());

    let receipt = fs::read_dir(cache.join("receipts"))
        .unwrap()
        .next()
        .unwrap()
        .unwrap()
        .path();
    let path = fs::read_dir(receipt)
        .unwrap()
        .find_map(|entry| {
            let path = entry.ok()?.path();
            (path
                .extension()
                .is_some_and(|extension| extension == "json"))
            .then_some(path)
        })
        .unwrap();
    let mut legacy: Value = serde_json::from_slice(&fs::read(&path).unwrap()).unwrap();
    legacy.as_object_mut().unwrap().remove("portable");
    fs::write(&path, serde_json::to_vec_pretty(&legacy).unwrap()).unwrap();

    assert_miss(&query(&deploy, &cache));
}

#[test]
fn query_rejects_a_receipt_bound_to_another_toolchain() {
    let (_base, dev, deploy, cache, _origin) = fixture();
    assert!(run(&dev, &cache, &["verify", "gate"]).status.success());
    assert!(query(&deploy, &cache)["matched"].as_bool().unwrap());

    let receipt = fs::read_dir(cache.join("receipts"))
        .unwrap()
        .next()
        .unwrap()
        .unwrap()
        .path();
    let path = fs::read_dir(receipt)
        .unwrap()
        .find_map(|entry| {
            let path = entry.ok()?.path();
            (path
                .extension()
                .is_some_and(|extension| extension == "json"))
            .then_some(path)
        })
        .unwrap();
    let mut mismatched: Value = serde_json::from_slice(&fs::read(&path).unwrap()).unwrap();
    mismatched["portable"]["toolchain"] = Value::String("different-toolchain".into());
    fs::write(&path, serde_json::to_vec_pretty(&mismatched).unwrap()).unwrap();

    assert_miss(&query(&deploy, &cache));
}

#[test]
fn query_requires_explicit_portable_opt_in() {
    let (_base, dev, deploy, cache, _origin) = fixture();
    local_only_profile(&dev);
    local_only_profile(&deploy);

    assert!(run(&dev, &cache, &["verify", "gate"]).status.success());
    let report = query(&deploy, &cache);

    assert!(!report["eligible"].as_bool().unwrap());
    assert!(!report["matched"].as_bool().unwrap());
}
